import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Existing
    settings: 'Settings',
    profile: 'Profile',
    appearance: 'Appearance',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    save: 'Save Changes',
    saved: 'Saved!',
    email: 'Email',
    role: 'Role',
    signOut: 'Sign Out',
    settingsDesc: 'Manage your account preferences and customize your experience.',
    profileDesc: 'Your account information synced from the authentication provider.',
    appearanceDesc: 'Customize how the platform looks and feels for you.',
    languageDesc: 'Choose your preferred display language.',
    themeDesc: 'Select a color scheme for the interface.',
    citizen: 'Citizen',
    government: 'Government',
    emergency: 'Rescue Service',
    volunteer: 'Volunteer',
    admin: 'Administrator',
    dashboard: 'Dashboard',
    welcomeBack: 'Welcome back',
    auth_welcomeBack: 'Welcome back',
    auth_join: 'Join Us',
    auth_noAccount: 'Don\'t have an account? ',
    auth_hasAccount: 'Already have an account? ',
    auth_signUp: 'Sign Up',
    auth_signIn: 'Sign In',
    auth_regSuccess: 'Registration successful! You may now sign in.',
    auth_accountType: 'Account Type',
    auth_govAuth: 'Government Authority',
    auth_volunteerResp: 'Volunteer Responder',
    auth_emailAddr: 'Email Address',
    auth_password: 'Password',
    auth_processing: 'Processing...',
    auth_createAccount: 'Create Account',

    // Navbar & Sidebar
    nav_airQuality: 'Air Quality Model',
    nav_dataPrep: 'Data Preprocessing',
    nav_geoAI: 'GeoAI Accessibility',
    nav_integration: 'Integration Service',
    nav_traffic: 'Traffic Model',
    nav_myHub: 'My Hub',
    nav_routingMap: 'Routing & Map',
    nav_eventsMap: 'Events Map',
    nav_volunteerBoard: 'Volunteer Board',
    nav_emergencies: 'Emergencies',
    nav_aiModels: 'AI Models',
    nav_about: 'About',
    nav_pendingRole: 'Pending Role',
    nav_pending: 'Pending',
    nav_lightMode: 'Light Mode',
    nav_darkMode: 'Dark Mode',
    nav_signOut: 'Sign out',
    nav_signIn: 'Sign In',
    sidebar_navigation: 'Navigation',
    sidebar_activeRole: 'Active Role',

    // Footer
    footer_desc: "Level-up your city's accessibility. Map your accessible journey and connect instantly with nearby volunteers.",
    footer_platform: 'Platform',
    footer_signInReg: 'Sign In / Register',
    footer_interactiveMap: 'Interactive Map',
    footer_legal: 'Legal',
    footer_privacyPolicy: 'Privacy Policy',
    footer_termsService: 'Terms of Service',

    // Landing Page
    landing_hero1: 'Level-up your city’s',
    landing_hero2: 'accessibility.',
    landing_desc: 'The ultimate navigation tool. Map your accessible journey and connect instantly with nearby volunteers when you need a little extra support.',
    landing_getStarted: 'Get Started',
    landing_planRouteText: 'Plan Your Route',
    landing_startPoint: 'Starting point',
    landing_whereTo: 'Where to?',
    landing_routeBtn: 'Route',
    landing_planRouteBtn: 'Plan Route',
    landing_useCurrentLoc: 'Use my current location',
    landing_moveCurrentLoc: 'Move to current location',
  },
  ru: {
    // Existing
    settings: 'Настройки',
    profile: 'Профиль',
    appearance: 'Внешний вид',
    language: 'Язык',
    theme: 'Тема',
    light: 'Светлая',
    dark: 'Тёмная',
    system: 'Системная',
    save: 'Сохранить',
    saved: 'Сохранено!',
    email: 'Эл. почта',
    role: 'Роль',
    signOut: 'Выйти',
    settingsDesc: 'Управляйте настройками аккаунта и настройте интерфейс.',
    profileDesc: 'Информация вашего аккаунта из системы аутентификации.',
    appearanceDesc: 'Настройте внешний вид платформы под себя.',
    languageDesc: 'Выберите предпочтительный язык интерфейса.',
    themeDesc: 'Выберите цветовую схему для интерфейса.',
    citizen: 'Гражданин',
    government: 'Гос. орган',
    emergency: 'Спасательная служба',
    volunteer: 'Волонтёр',
    admin: 'Администратор',
    dashboard: 'Панель управления',
    welcomeBack: 'С возвращением',

    // Navbar & Sidebar
    nav_airQuality: 'Модель качества воздуха',
    nav_dataPrep: 'Предобработка данных',
    nav_geoAI: 'GeoAI Доступность',
    nav_integration: 'Сервис интеграции',
    nav_traffic: 'Модель трафика',
    nav_myHub: 'Мой хаб',
    nav_routingMap: 'Маршруты и карта',
    nav_eventsMap: 'Карта событий',
    nav_volunteerBoard: 'Доска волонтёров',
    nav_emergencies: 'ЧС',
    nav_aiModels: 'ИИ Модели',
    nav_about: 'О нас',
    nav_pendingRole: 'Ожидание роли',
    nav_pending: 'Ожидание',
    nav_lightMode: 'Светлая тема',
    nav_darkMode: 'Тёмная тема',
    nav_signOut: 'Выйти',
    nav_signIn: 'Войти',
    sidebar_navigation: 'Навигация',
    sidebar_activeRole: 'Активная роль',

    // Footer
    footer_desc: "Повысьте доступность вашего города. Прокладывайте удобные маршруты и мгновенно связывайтесь с ближайшими волонтёрами.",
    footer_platform: 'Платформа',
    footer_signInReg: 'Войти / Регистрация',
    footer_interactiveMap: 'Интерактивная карта',
    footer_legal: 'Правовая информация',
    footer_privacyPolicy: 'Политика конфиденциальности',
    footer_termsService: 'Условия использования',

    // Landing Page
    landing_hero1: 'Улучшите доступность',
    landing_hero2: 'вашего города.',
    landing_desc: 'Лучший инструмент навигации. Прокладывайте доступный маршрут и мгновенно связывайтесь с волонтёрами, когда нужна дополнительная помощь.',
    landing_getStarted: 'Начать',
    landing_planRouteText: 'Спланировать маршрут',
    landing_startPoint: 'Пункт отправления',
    landing_whereTo: 'Куда направляетесь?',
    landing_routeBtn: 'Маршрут',
    landing_planRouteBtn: 'План маршрута',
    landing_useCurrentLoc: 'Использовать текущее местоположение',
    landing_moveCurrentLoc: 'К текущему местоположению',
  },
  kk: {
    // Existing
    settings: 'Баптаулар',
    profile: 'Профиль',
    appearance: 'Сыртқы түрі',
    language: 'Тіл',
    theme: 'Тақырып',
    light: 'Жарық',
    dark: 'Қараңғы',
    system: 'Жүйелік',
    save: 'Сақтау',
    saved: 'Сақталды!',
    email: 'Эл. пошта',
    role: 'Рөл',
    signOut: 'Шығу',
    settingsDesc: 'Аккаунт баптауларын басқарыңыз және тәжірибеңізді теңшеңіз.',
    profileDesc: 'Аутентификация жүйесінен алынған аккаунт ақпараты.',
    appearanceDesc: 'Платформаның сыртқы түрін реттеңіз.',
    languageDesc: 'Қалаған интерфейс тілін таңдаңыз.',
    themeDesc: 'Интерфейс үшін түс схемасын таңдаңыз.',
    citizen: 'Азамат',
    government: 'Мемлекеттік орган',
    emergency: 'Құтқару қызметі',
    volunteer: 'Волонтёр',
    admin: 'Әкімші',
    dashboard: 'Басқару тақтасы',
    welcomeBack: 'Қош келдіңіз',

    // Navbar & Sidebar
    nav_airQuality: 'Ауа сапасы моделі',
    nav_dataPrep: 'Деректерді өңдеу',
    nav_geoAI: 'GeoAI Қолжетімділігі',
    nav_integration: 'Интеграция қызметі',
    nav_traffic: 'Көлік қозғалысы моделі',
    nav_myHub: 'Менің хабым',
    nav_routingMap: 'Маршрут және карта',
    nav_eventsMap: 'Оқиғалар картасы',
    nav_volunteerBoard: 'Волонтёрлер тақтасы',
    nav_emergencies: 'ТЖ',
    nav_aiModels: 'ЖИ Модельдері',
    nav_about: 'Біз туралы',
    nav_pendingRole: 'Рөлді күту',
    nav_pending: 'Күтілуде',
    nav_lightMode: 'Жарық тақырып',
    nav_darkMode: 'Қараңғы тақырып',
    nav_signOut: 'Шығу',
    nav_signIn: 'Кіру',
    sidebar_navigation: 'Навигация',
    sidebar_activeRole: 'Белсенді рөл',

    // Footer
    footer_desc: "Қалаңыздың қолжетімділігін арттырыңыз. Қолайлы маршрут құрыңыз және жақын маңдағы еріктілермен лезде байланысыңыз.",
    footer_platform: 'Платформа',
    footer_signInReg: 'Кіру / Тіркелу',
    footer_interactiveMap: 'Интерактивті карта',
    footer_legal: 'Құқықтық ақпарат',
    footer_privacyPolicy: 'Құпиялылық саясаты',
    footer_termsService: 'Қолдану шарттары',

    // Landing Page
    landing_hero1: 'Қалаңыздың қолжетімділігін',
    landing_hero2: 'арттырыңыз.',
    landing_desc: 'Ең жақсы навигация құралы. Қолжетімді маршрут құрыңыз және қосымша көмек қажет болғанда еріктілермен лезде байланысыңыз.',
    landing_getStarted: 'Бастау',
    landing_planRouteText: 'Маршрутты жоспарлау',
    landing_startPoint: 'Бастапқы нүкте',
    landing_whereTo: 'Қайда бара жатырсыз?',
    landing_routeBtn: 'Маршрут',
    landing_planRouteBtn: 'Маршрут жоспары',
    landing_useCurrentLoc: 'Ағымдағы орынды пайдалану',
    landing_moveCurrentLoc: 'Ағымдағы орынға өту',
    // Auth
    auth_welcomeBack: 'Welcome back',
    auth_join: 'Join sonar',
    auth_noAccount: "Don't have an account? ",
    auth_hasAccount: "Already have an account? ",
    auth_signUp: 'Sign up',
    auth_signIn: 'Sign in',
    auth_regSuccess: 'Registration successful! Please sign in.',
    auth_accountType: 'Account Type',
    auth_govAuth: 'Government / Authority',
    auth_volunteerResp: 'Volunteer Responder',
    auth_emailAddr: 'Email address',
    auth_password: 'Password',
    auth_processing: 'Processing...',
    auth_createAccount: 'Create Account',

    // Profile Details
    profile_anonymous: 'Anonymous User',
    profile_edit: 'Edit Profile',
    profile_cancel: 'Cancel',
    profile_saving: 'Saving...',
    profile_personalInfo: 'Personal Information',
    profile_firstName: 'First Name',
    profile_egJohn: 'e.g. John',
    profile_notSpecified: 'Not specified',
    profile_lastName: 'Last Name (Optional)',
    profile_egDoe: 'e.g. Doe',
    profile_demographics: 'Demographics',
    profile_city: 'City (By Location)',
    profile_egAlmaty: 'e.g. Almaty',
    profile_age: 'Age (Optional)',
    profile_egAge: 'e.g. 25',
    profile_yearsOld: 'years old',

    // Events & Map
    cat_infrastructure: 'Infrastructure',
    cat_emergency: 'Emergency',
    cat_urban: 'Urban',
    cat_events: 'Events',
    catDesc_infrastructure: 'Construction, pipes, roads',
    catDesc_emergency: 'Accidents, fire, fallen tree',
    catDesc_urban: 'Trash, broken lights',
    catDesc_events: 'Fair, concert, road closure',
    status_all: 'All Statuses',
    status_planned: 'Planned',
    status_active: 'Active',
    status_resolving: 'Resolving',
    impact_low: 'Low',
    impact_medium: 'Medium',
    impact_high: 'High',
    impactBadge_low: 'Low Impact',
    impactBadge_medium: 'Medium Impact',
    impactBadge_high: 'High Impact',

    map_filters: 'Filters',
    map_all: 'All',
    map_eventsCount: 'events',
    map_tapPin: '📍 Tap the map to place your event pin',
    map_goToLocation: 'Go to my location',
    map_reportEvent: 'Report Event',

    modal_reportEvent: 'Report Event',
    modal_aiRefine: 'AI Refinement',
    modal_eventName: 'Event Name *',
    modal_egRoad: 'e.g. Road construction on Abay St.',
    modal_desc: 'Description',
    modal_briefDesc: "Briefly describe what's happening...",
    modal_refiningAI: 'Refining with AI...',
    modal_refinedAI: '✓ Refined — Re-run AI',
    modal_autoFillAI: 'Auto-fill with AI',
    modal_aiAppliedMsg: 'AI has auto-filled the fields below. Review and adjust as needed.',
    modal_category: 'Category *',
    modal_photoVideo: 'Photo / Video',
    modal_tapAddPhoto: 'Tap to add photo',
    modal_photoCredibility: 'A photo adds more credibility to your report',
    modal_timestamp: 'Timestamp: ',
    modal_addDetails: '🎯 Add more details (optional)',
    modal_impactLevel: 'Impact Level',
    modal_status: 'Status',
    modal_quickTags: 'Quick Tags',
    modal_submitting: 'Submitting...',
    modal_submitReport: 'Submit Report',

    panel_radius: ' radius',
    panel_tags: 'Tags',
    panel_desc: 'Description',
    panel_trustScore: 'Trust Score',
    panel_confirm: 'Confirm',
    panel_notHere: 'Not here',
    panel_reported: 'Reported ',
    panel_timeUnknown: 'Unknown',
    panel_timeJustNow: 'Just now',
    panel_timeMinsAgo: 'm ago',
    panel_timeHrsAgo: 'h ago',
    panel_timeDaysAgo: 'd ago',

    // Widgets (Chat, Gamification, MapRouting, Alerts)
    chat_serviceNotConnected: 'AI service is not yet connected. Please check back later.',
    chat_assistant: 'AI Assistant',
    chat_poweredBy: 'Powered by OpenAI',
    chat_typeRequest: 'Type your request...',

    gamification_levelX: 'Level {level} Volunteer',
    gamification_pts: 'Pts',
    gamification_helps: 'Helps',
    gamification_lv: 'Lv. ',
    gamification_rank: 'Rank',

    routing_title: 'Accessible Routing',
    routing_placeholder: 'Where do you want to go?',
    routing_routing: 'Routing...',
    routing_routeBtn: 'Route',
    routing_errorNoDest: 'Please enter a destination first.',
    routing_errorCalc: 'Failed to calculate accessible route.',
    routing_errorFetch: 'Unable to fetch route guidance.',
    routing_geoAI: 'GeoAI Accessibility Insights',
    routing_score: 'Score: ',
    routing_next: 'Next: ',
    routing_moveToLoc: 'Move to current location',

    alert_emergency: 'Emergency Alert',

    // Dashboards - Admin
    admin_title: 'Admin Command Center',
    admin_subtitle: 'Real-time platform overview and incident tracking.',
    admin_platformActive: 'Platform Active',
    admin_totalUsers: 'Total Registered Users',
    admin_activeVolunteers: 'Active Volunteers',
    admin_liveEvents: 'Live Incident Events',
    admin_liveMap: 'Live Incident Map',
    admin_tracking: 'Tracking',
    admin_active: 'Active',
    admin_recentFeed: 'Recent Activity Feed',
    admin_noRecentActivity: 'No recent activity recorded.',
    admin_status: 'Status: ',

    // Dashboards - Citizen
    citizen_title: 'Citizen Services',
    citizen_welcomeText: 'Welcome, {email}. How can we assist your mobility today?',
    citizen_reqAssistance: 'Request Physical Assistance',
    citizen_reqAssistanceDesc: 'If you need immediate help with stairs, boarding transit, or crossing a dangerous intersection, broadcast a request to nearby vetted volunteers.',
    citizen_broadcastReq: 'Broadcast Help Request',
    citizen_connectingVol: 'Connecting to Volunteer Network...',

    // Dashboards - Emergency
    emerg_title: 'Emergencies',
    emerg_activeAlerts: 'Active Critical Alerts',
    emerg_noActive: 'No active emergencies tracked.',
    emerg_dispatch: 'Dispatch',
    emerg_dispatched: 'Dispatched / Resolving',
    emerg_dispatchedAt: 'Dispatched at ',
    emerg_noDispatched: 'No recently dispatched units.',
    emerg_selfReportTitle: 'Accident Self-report',
    emerg_eventCat: 'Event Category *',
    emerg_preciseLoc: 'Precise Location *',
    emerg_locPlaceholder: 'Address, intersection, or GPS pin...',
    emerg_dateTime: 'Date and Time of Observation *',
    emerg_severity: 'Severity / Urgency Level *',
    emerg_impact: 'Impact on Surroundings',
    emerg_detailedDesc: 'Detailed Description',
    emerg_descPlaceholder: 'Optional context (e.g. leaking fluids, waiting for tow)...',
    emerg_visualEvid: 'Visual Evidence',
    emerg_reporterInfo: 'Reporter Information',
    emerg_submitAnon: 'Submit Anonymously',
    emerg_yourName: 'Your Name',
    emerg_contactOpt: 'Email or Phone (optional)',
    emerg_submitReport: 'Submit Report',
    emerg_cat_traffic: 'Traffic Accident',
    emerg_cat_road: 'Road Construction',
    emerg_cat_poth: 'Pothole',
    emerg_cat_tree: 'Fallen Tree',
    emerg_cat_flood: 'Flooding',
    emerg_cat_event: 'Public Event',
    emerg_imp_lanes: 'Lanes Blocked',
    emerg_imp_side: 'Sidewalk Closed',
    emerg_imp_power: 'Power Outage',
    emerg_imp_traffic: 'Heavy Traffic',
    emerg_imp_noise: 'Loud Noise',
    emerg_imp_hazard: 'Hazard to Pedestrians',
    emerg_sev_low: 'Low',
    emerg_sev_med: 'Medium',
    emerg_sev_high: 'High',
    emerg_sev_crit: 'Critical',

    // Dashboards - Government
    gov_title: 'City Intelligence Hub',
    gov_subtitle: 'AI-Driven Infrastructure & Mobility Analytics',
    gov_trafficAgent: 'Traffic Optimization Agent',
    gov_zonePlaceholder: 'Enter City Zone...',
    gov_analyzing: 'Analyzing...',
    gov_runAnalysis: 'Run Analysis',
    gov_conf: 'Conf: ',
    gov_aiRec: 'AI Recommendation:',
    gov_liveMetrics: 'Live City Metrics',
    gov_routesReported: 'Accessible Routes Reported',
    gov_volNetwork: 'Volunteer Network Size',

    // Dashboards - Volunteer
    vol_title: 'Volunteer Hub',
    vol_pointsLevel: '{points} Points (Level {level})',
    vol_activeSearching: 'Active & Searching',
    vol_scanning: 'Scanning...',
    vol_activeReqs: 'Active Requests Nearby',
    vol_noActiveReqs: 'No active assistance requests in your area.',
    vol_assistanceAsap: 'Assistance needed ASAP.',
    vol_acceptMapRoute: 'Accept & Map Route',

    // Models - AirQualityModel
    aqm_title: 'Air Quality Hybrid Model',
    aqm_subtitle: 'LSTM + XGBoost + CatBoost Ensemble',
    aqm_desc: 'A hybrid deep-learning ensemble for urban air quality forecasting. An LSTM encoder captures temporal pollutant dynamics, then XGBoost and CatBoost heads perform the final regression and classification — averaged for robust predictions.',
    aqm_runInference: 'Run Inference',
    aqm_uploadCSV: 'Upload a CSV with columns: DATE_OCC, TIME_OCC, Lat, Lon, PT08.S1(CO), Temperature_C, RH% (or RH_%), Wind_Speed, C6H6(GT), AQI',
    aqm_clickToSelect: 'Click to select CSV',
    aqm_dragDrop: 'or drag and drop',
    aqm_processing: 'Processing...',
    aqm_predict: 'Predict',
    aqm_predictions: 'Predictions',
    aqm_row: 'Row',
    aqm_co: 'CO Concentration',
    aqm_c6h6: 'C6H6 Concentration',
    aqm_aqi: 'AQI',
    aqm_category: 'Category',
    aqm_architecture: 'Architecture',
    aqm_lstm: 'LSTM Encoder',
    aqm_lstm_desc: 'Multi-layer LSTM captures temporal dependencies across sliding windows of sensor readings, outputting a compact embedding.',
    aqm_fusion: 'Feature Fusion',
    aqm_fusion_desc: 'LSTM embeddings are concatenated with static/instantaneous features (Lat, Lon, Wind Speed) before passing to ensemble heads.',
    aqm_ensemble: 'Ensemble Heads',
    aqm_ensemble_desc: 'Dual XGBoost + CatBoost heads for regression (C6H6, CO) and classification (AQI). Predictions are averaged for stability.',
    aqm_targets: 'Prediction Targets',
    aqm_regression: 'Regression',
    aqm_multiclass: 'Multi-class',
    aqm_hyperparameters: 'Hyperparameters',

    // Models - DataPreprocessing
    dp_title: 'Data Preprocessing Pipeline',
    dp_subtitle: 'Traffic Congestion Feature Engineering',
    dp_desc: 'Transforms raw traffic sensor + contextual inputs into model-ready features using sklearn pipelines.',
    dp_preview: 'Preview Dataset',
    dp_uploadDesc: 'Upload a traffic CSV to preview raw data. Preprocessing runs server-side during Traffic Model inference.',
    dp_previewRows: 'Preview first 20 rows',
    dp_rawPreview: 'Raw Data Preview',
    dp_pipelineArch: 'Pipeline Architecture',
    dp_step1: 'Raw Sensor Data',
    dp_step2: 'Temporal Extraction',
    dp_step3: 'Imputation',
    dp_step4: 'Scaling / Encoding',
    dp_step5: 'Model-Ready Matrix',
    dp_temporalFeat: 'Temporal Features',
    dp_temp1: 'Cyclic 24 h encoding',
    dp_temp2: 'Cyclic 7-day encoding',
    dp_temp3: 'Binary weekend flag',
    dp_temp4: 'US Federal holiday flag',
    dp_numeric: 'Numeric Features',
    dp_numDesc: 'Median imputation → StandardScaler normalization',
    dp_categorical: 'Categorical Features',
    dp_catDesc: 'Most-frequent imputation → OneHotEncoder',

    // Models - GeoAIAccessibility
    geoai_title: 'GeoAI Accessibility Router',
    geoai_subtitle: 'Wheelchair-First GNN-Style Navigation',
    geoai_desc: 'A graph-based routing engine that builds an accessibility-aware graph from node data (tactile paving, wheelchair access, kerb/ramp profiles), applies GNN-inspired message passing to smooth scores, then runs Dijkstra with accessibility penalties.',
    geoai_planRoute: 'Plan Route',
    geoai_start: 'Start (geoid or address)',
    geoai_dest: 'Destination (geoid or address)',
    geoai_computing: 'Computing...',
    geoai_findRoute: 'Find Route',
    geoai_routeResult: 'Route Result',
    geoai_distance: 'Distance',
    geoai_time: 'Time',
    geoai_accessibility: 'Accessibility',
    geoai_confidence: 'Confidence',
    geoai_warnings: 'Warnings',
    geoai_routeSteps: 'Route Steps',
    geoai_howItWorks: 'How It Works',
    geoai_step1: '1. Score Nodes',
    geoai_step1Desc: 'Each node gets a weighted accessibility score from tactile, wheelchair, kerb, and signal features.',
    geoai_step2: '2. Message Passing',
    geoai_step2Desc: 'Scores are smoothed over the graph topology through iterative neighborhood blending (3 rounds, 35% blend).',
    geoai_step3: '3. Dijkstra Routing',
    geoai_step3Desc: 'Shortest path uses edge cost = distance × accessibility penalty × slope penalty for wheelchair-optimal routes.',
    geoai_featureWeights: 'Accessibility Feature Weights',
    geoai_feat1: 'Wheelchair Access',
    geoai_feat2: 'Tactile Paving',
    geoai_feat3: 'Kerb / Ramp',
    geoai_feat4: 'Audio Signals',
    geoai_params: 'Model Parameters',
    geoai_param1: 'Message Passing Steps',
    geoai_param2: 'Neighborhood Blend',
    geoai_param3: 'Base Traversal Speed',
    geoai_param4: 'Slope Penalty Threshold',

    // Models - IntegrationService
    int_title: 'Integration Service',
    int_subtitle: 'Real-Time Air Quality Inference Wrapper',
    int_desc: 'A production-ready service wrapper around the Air Quality Hybrid Model. Maintains a rolling history buffer, auto-pads short sequences for single-event inference, and returns JSON-serializable prediction results.',
    int_simulate: 'Simulate Sensor Event',
    int_predResult: 'Prediction Result',
    int_reqFlow: 'Request Flow',
    int_step1: 'Sensor Event',
    int_step2: 'History Buffer',
    int_step3: 'Sequence Padding',
    int_step4: 'Model Inference',
    int_step5: 'JSON Response',
    int_rollingBuffer: 'Rolling History Buffer',
    int_bufferStrat: 'Buffer Strategy',
    int_bufferStratDesc: 'Fixed-size deque (window_size + horizon). New events append, oldest evicted when full.',
    int_autoPad: 'Auto-Padding',
    int_autoPadDesc: 'Short buffers pad by duplicating the earliest row to reach minimum sequence length.',
    int_resSchema: 'Response Schema',
    int_field: 'Field',
    int_type: 'Type',
    int_descTable: 'Description',
    int_descCO: 'CO level',
    int_descC6H6: 'C6H6 level',
    int_descAQI: 'Air Quality Index',
    int_descCat: 'AQI category',

    // Models - TrafficModel
    traf_title: 'Traffic Congestion Model',
    traf_subtitle: 'RandomForest Classifier with Pluggable Backend',
    traf_desc: 'Multi-class congestion classifier using a RandomForest ensemble. Ingests real-time traffic metrics including vehicle counts, speeds, road occupancy, weather, acoustic stress (horn events), and CO2 levels to predict Low / Medium / High congestion.',
    traf_predCongestion: 'Predicted Congestion',
    traf_congLevels: 'Congestion Levels',
    traf_descFree: 'Free-flowing traffic',
    traf_descMod: 'Moderate congestion',
    traf_descSev: 'Severe congestion / gridlock',
    traf_inputFeat: 'Input Feature Groups',
    traf_grp1: 'Traffic State',
    traf_grp2: 'Vehicle Mix',
    traf_grp3: 'Control & Context',
    traf_grp4: 'Stress Signals',
    traf_rfBackend: 'RandomForest Backend',
    traf_p1: 'Estimators',
    traf_p2: 'Max Depth',
    traf_p3: 'Min Samples Leaf',
    traf_p4: 'Class Weight',
    traf_plugDesign: 'Pluggable Design',
    traf_plugDesc: 'The model backend follows a simple ModelBackend protocol (fit / predict). The RandomForest can be swapped with a BiLSTM or any sequence model without touching the preprocessing pipeline or API layer.',
  },
  ru: {
    // Existing
    settings: 'Настройки',
    profile: 'Профиль',
    appearance: 'Внешний вид',
    language: 'Язык',
    theme: 'Тема',
    light: 'Светлая',
    dark: 'Тёмная',
    system: 'Системная',
    save: 'Сохранить',
    saved: 'Сохранено!',
    email: 'Эл. почта',
    role: 'Роль',
    signOut: 'Выйти',
    settingsDesc: 'Управляйте настройками аккаунта и настройте интерфейс.',
    profileDesc: 'Информация вашего аккаунта из системы аутентификации.',
    appearanceDesc: 'Настройте внешний вид платформы под себя.',
    languageDesc: 'Выберите предпочтительный язык интерфейса.',
    themeDesc: 'Выберите цветовую схему для интерфейса.',
    citizen: 'Гражданин',
    government: 'Гос. орган',
    emergency: 'Спасательная служба',
    volunteer: 'Волонтёр',
    admin: 'Администратор',
    dashboard: 'Панель управления',
    welcomeBack: 'С возвращением',

    // Navbar & Sidebar
    nav_airQuality: 'Модель качества воздуха',
    nav_dataPrep: 'Предобработка данных',
    nav_geoAI: 'GeoAI Доступность',
    nav_integration: 'Сервис интеграции',
    nav_traffic: 'Модель трафика',
    nav_myHub: 'Мой хаб',
    nav_routingMap: 'Маршруты и карта',
    nav_eventsMap: 'Карта событий',
    nav_volunteerBoard: 'Доска волонтёров',
    nav_emergencies: 'ЧС',
    nav_aiModels: 'ИИ Модели',
    nav_about: 'О нас',
    nav_pendingRole: 'Ожидание роли',
    nav_pending: 'Ожидание',
    nav_lightMode: 'Светлая тема',
    nav_darkMode: 'Тёмная тема',
    nav_signOut: 'Выйти',
    nav_signIn: 'Войти',
    sidebar_navigation: 'Навигация',
    sidebar_activeRole: 'Активная роль',

    // Footer
    footer_desc: "Повысьте доступность вашего города. Прокладывайте удобные маршруты и мгновенно связывайтесь с ближайшими волонтёрами.",
    footer_platform: 'Платформа',
    footer_signInReg: 'Войти / Регистрация',
    footer_interactiveMap: 'Интерактивная карта',
    footer_legal: 'Правовая информация',
    footer_privacyPolicy: 'Политика конфиденциальности',
    footer_termsService: 'Условия использования',

    // Landing Page
    landing_hero1: 'Улучшите доступность',
    landing_hero2: 'вашего города.',
    landing_desc: 'Лучший инструмент навигации. Прокладывайте доступный маршрут и мгновенно связывайтесь с волонтёрами, когда нужна дополнительная помощь.',
    landing_getStarted: 'Начать',
    landing_planRouteText: 'Спланировать маршрут',
    landing_startPoint: 'Пункт отправления',
    landing_whereTo: 'Куда направляетесь?',
    landing_routeBtn: 'Маршрут',
    landing_planRouteBtn: 'План маршрута',
    landing_useCurrentLoc: 'Использовать текущее местоположение',
    landing_moveCurrentLoc: 'К текущему местоположению',

    // Auth
    auth_welcomeBack: 'С возвращением',
    auth_join: 'Присоединиться к sonar',
    auth_noAccount: "Нет аккаунта? ",
    auth_hasAccount: "Уже есть аккаунт? ",
    auth_signUp: 'Зарегистрироваться',
    auth_signIn: 'Войти',
    auth_regSuccess: 'Регистрация успешна! Пожалуйста, войдите.',
    auth_accountType: 'Тип аккаунта',
    auth_govAuth: 'Гос. орган / Управление',
    auth_volunteerResp: 'Волонтёр-спасатель',
    auth_emailAddr: 'Эл. почта',
    auth_password: 'Пароль',
    auth_processing: 'Обработка...',
    auth_createAccount: 'Создать аккаунт',

    // Profile Details
    profile_anonymous: 'Анонимный пользователь',
    profile_edit: 'Редактировать профиль',
    profile_cancel: 'Отмена',
    profile_saving: 'Сохранение...',
    profile_personalInfo: 'Личная информация',
    profile_firstName: 'Имя',
    profile_egJohn: 'напр. Иван',
    profile_notSpecified: 'Не указано',
    profile_lastName: 'Фамилия (необязательно)',
    profile_egDoe: 'напр. Иванов',
    profile_demographics: 'Демография',
    profile_city: 'Город (по местоположению)',
    profile_egAlmaty: 'напр. Алматы',
    profile_age: 'Возраст (необязательно)',
    profile_egAge: 'напр. 25',
    profile_yearsOld: 'лет',

    // Events & Map
    cat_infrastructure: 'Инфраструктура',
    cat_emergency: 'ЧС',
    cat_urban: 'Городская среда',
    cat_events: 'Мероприятия',
    catDesc_infrastructure: 'Стройка, трубы, дороги',
    catDesc_emergency: 'Аварии, пожар, упавшее дерево',
    catDesc_urban: 'Мусор, неработающие фонари',
    catDesc_events: 'Ярмарка, концерт, перекрытие дороги',
    status_all: 'Все статусы',
    status_planned: 'Запланировано',
    status_active: 'Активно',
    status_resolving: 'Решается',
    impact_low: 'Низкий',
    impact_medium: 'Средний',
    impact_high: 'Высокий',
    impactBadge_low: 'Низкий уровень',
    impactBadge_medium: 'Средний уровень',
    impactBadge_high: 'Высокий уровень',

    map_filters: 'Фильтры',
    map_all: 'Все',
    map_eventsCount: 'событий',
    map_tapPin: '📍 Нажмите на карту, чтобы установить метку события',
    map_goToLocation: 'Мое местоположение',
    map_reportEvent: 'Сообщить о событии',

    modal_reportEvent: 'Сообщить о событии',
    modal_aiRefine: 'ИИ Улучшение',
    modal_eventName: 'Название события *',
    modal_egRoad: 'напр. Ремонт дороги на ул. Абая',
    modal_desc: 'Описание',
    modal_briefDesc: 'Кратко опишите, что происходит...',
    modal_refiningAI: 'Обработка ИИ...',
    modal_refinedAI: '✓ Улучшено — Повторить ИИ',
    modal_autoFillAI: 'Автозаполнение (ИИ)',
    modal_aiAppliedMsg: 'ИИ автоматически заполнил поля ниже. Проверьте и при необходимости измените.',
    modal_category: 'Категория *',
    modal_photoVideo: 'Фото / Видео',
    modal_tapAddPhoto: 'Нажмите, чтобы добавить фото',
    modal_photoCredibility: 'Фотография повышает доверие к вашему отчету',
    modal_timestamp: 'Время создания: ',
    modal_addDetails: '🎯 Добавить детали (необязательно)',
    modal_impactLevel: 'Уровень влияния',
    modal_status: 'Статус',
    modal_quickTags: 'Быстрые теги',
    modal_submitting: 'Отправка...',
    modal_submitReport: 'Отправить отчет',

    panel_radius: ' радиус',
    panel_tags: 'Теги',
    panel_desc: 'Описание',
    panel_trustScore: 'Индекс доверия',
    panel_confirm: 'Подтверждаю',
    panel_notHere: 'Этого здесь нет',
    panel_reported: 'Сообщено ',
    panel_timeUnknown: 'Неизвестно',
    panel_timeJustNow: 'Только что',
    panel_timeMinsAgo: 'м назад',
    panel_timeHrsAgo: 'ч назад',
    panel_timeDaysAgo: 'д назад',

    // Widgets (Chat, Gamification, MapRouting, Alerts)
    chat_serviceNotConnected: 'ИИ-сервис еще не подключен. Пожалуйста, зайдите позже.',
    chat_assistant: 'ИИ Ассистент',
    chat_poweredBy: 'На базе OpenAI',
    chat_typeRequest: 'Введите ваш запрос...',

    gamification_levelX: 'Волонтёр {level} уровня',
    gamification_pts: 'Очки',
    gamification_helps: 'Помощь',
    gamification_lv: 'Ур. ',
    gamification_rank: 'Ранг',

    routing_title: 'Доступный маршрут',
    routing_placeholder: 'Куда вы хотите отправиться?',
    routing_routing: 'Маршрутизация...',
    routing_routeBtn: 'Маршрут',
    routing_errorNoDest: 'Пожалуйста, сначала введите пункт назначения.',
    routing_errorCalc: 'Не удалось рассчитать доступный маршрут.',
    routing_errorFetch: 'Не удалось получить инструкции по маршруту.',
    routing_geoAI: 'GeoAI Анализ доступности',
    routing_score: 'Оценка: ',
    routing_next: 'Далее: ',
    routing_moveToLoc: 'К текущему местоположению',

    alert_emergency: 'Экстренное оповещение',

    // Dashboards - Admin
    admin_title: 'Командный центр администратора',
    admin_subtitle: 'Обзор платформы в реальном времени и отслеживание инцидентов.',
    admin_platformActive: 'Платформа Активна',
    admin_totalUsers: 'Всего зарегистрированных пользователей',
    admin_activeVolunteers: 'Активные Волонтёры',
    admin_liveEvents: 'Текущие инциденты',
    admin_liveMap: 'Карта Инцидентов Автономно',
    admin_tracking: 'Отслеживается',
    admin_active: 'Активно',
    admin_recentFeed: 'Лента недавней активности',
    admin_noRecentActivity: 'Нет записей о недавней активности.',
    admin_status: 'Статус: ',

    // Dashboards - Citizen
    citizen_title: 'Услуги для граждан',
    citizen_welcomeText: 'Добро пожаловать, {email}. Чем мы можем помочь вашей мобильности сегодня?',
    citizen_reqAssistance: 'Запросить Физическую Помощь',
    citizen_reqAssistanceDesc: 'Если вам нужна немедленная помощь с лестницами, посадкой в транспорт или пересечением опасного перекрестка, отправьте запрос проверенным волонтёрам поблизости.',
    citizen_broadcastReq: 'Отправить Запрос о Помощи',
    citizen_connectingVol: 'Соединение с Сетью Волонтёров...',

    // Dashboards - Emergency
    emerg_title: 'Чрезвычайные ситуации',
    emerg_activeAlerts: 'Активные Критические Оповещения',
    emerg_noActive: 'Нет отслеживаемых активных ЧС.',
    emerg_dispatch: 'Отправить',
    emerg_dispatched: 'Отправлены / Разрешаются',
    emerg_dispatchedAt: 'Отправлено в ',
    emerg_noDispatched: 'Нет недавно отправленных единиц.',
    emerg_selfReportTitle: 'Самостоятельный отчет о происшествии',
    emerg_eventCat: 'Категория события *',
    emerg_preciseLoc: 'Точное местоположение *',
    emerg_locPlaceholder: 'Адрес, перекресток или GPS-метка...',
    emerg_dateTime: 'Дата и время наблюдения *',
    emerg_severity: 'Уровень серьезности / срочности *',
    emerg_impact: 'Влияние на окружающую среду',
    emerg_detailedDesc: 'Подробное описание',
    emerg_descPlaceholder: 'Опциональный контекст (например, утечка жидкостей, ожидание эвакуатора)...',
    emerg_visualEvid: 'Визуальные доказательства',
    emerg_reporterInfo: 'Информация о сообщающем',
    emerg_submitAnon: 'Отправить анонимно',
    emerg_yourName: 'Ваше имя',
    emerg_contactOpt: 'Эл. почта или телефон (опционально)',
    emerg_submitReport: 'Отправить отчет',
    emerg_cat_traffic: 'Дорожно-транспортное происшествие',
    emerg_cat_road: 'Ремонт дороги',
    emerg_cat_poth: 'Яма',
    emerg_cat_tree: 'Упавшее дерево',
    emerg_cat_flood: 'Наводнение',
    emerg_cat_event: 'Общественное мероприятие',
    emerg_imp_lanes: 'Полосы заблокированы',
    emerg_imp_side: 'Тротуар закрыт',
    emerg_imp_power: 'Отключение электричества',
    emerg_imp_traffic: 'Плотный трафик',
    emerg_imp_noise: 'Сильный шум',
    emerg_imp_hazard: 'Опасность для пешеходов',
    emerg_sev_low: 'Низкий',
    emerg_sev_med: 'Средний',
    emerg_sev_high: 'Высокий',
    emerg_sev_crit: 'Критический',

    // Dashboards - Government
    gov_title: 'Центр Интеллекта Города',
    gov_subtitle: 'Аналитика инфраструктуры и мобильности на базе ИИ',
    gov_trafficAgent: 'Агент Оптимизации Трафика',
    gov_zonePlaceholder: 'Введите зону города...',
    gov_analyzing: 'Анализ...',
    gov_runAnalysis: 'Запустить анализ',
    gov_conf: 'Уверенность: ',
    gov_aiRec: 'Рекомендация ИИ:',
    gov_liveMetrics: 'Живые Метрики Города',
    gov_routesReported: 'Сообщенные доступные маршруты',
    gov_volNetwork: 'Размер сети волонтёров',

    // Dashboards - Volunteer
    vol_title: 'Центр Волонтёров',
    vol_pointsLevel: '{points} Очков (Уровень {level})',
    vol_activeSearching: 'Активен и в поиске',
    vol_scanning: 'Сканирование...',
    vol_activeReqs: 'Активные запросы поблизости',
    vol_noActiveReqs: 'В вашем районе нет активных запросов о помощи.',
    vol_assistanceAsap: 'Помощь нужна как можно скорее.',
    vol_acceptMapRoute: 'Принять и проложить маршрут',

    // Models - AirQualityModel
    aqm_title: 'Гибридная модель качества воздуха',
    aqm_subtitle: 'Ансамбль LSTM + XGBoost + CatBoost',
    aqm_desc: 'Гибридный ансамбль глубокого обучения для прогнозирования качества воздуха в городах. Кодировщик LSTM улавливает временную динамику загрязнителей, затем модули XGBoost и CatBoost выполняют окончательную регрессию и классификацию — усредняя для надежных прогнозов.',
    aqm_runInference: 'Запустить вывод',
    aqm_uploadCSV: 'Загрузите CSV с колонками: DATE_OCC, TIME_OCC, Lat, Lon, PT08.S1(CO), Temperature_C, RH% (or RH_%), Wind_Speed, C6H6(GT), AQI',
    aqm_clickToSelect: 'Нажмите, чтобы выбрать CSV',
    aqm_dragDrop: 'или перетащите сюда',
    aqm_processing: 'Обработка...',
    aqm_predict: 'Предсказать',
    aqm_predictions: 'Предсказания',
    aqm_row: 'Строка',
    aqm_co: 'Концентрация CO',
    aqm_c6h6: 'Концентрация C6H6',
    aqm_aqi: 'Индекс качества воздуха (AQI)',
    aqm_category: 'Категория',
    aqm_architecture: 'Архитектура',
    aqm_lstm: 'Кодировщик LSTM',
    aqm_lstm_desc: 'Многослойный LSTM фиксирует временные зависимости в скользящих окнах показаний датчиков, выдавая компактное вложение.',
    aqm_fusion: 'Слияние признаков',
    aqm_fusion_desc: 'Вложения LSTM объединяются со статическими/мгновенными признаками (Широта, Долгота, Скорость ветра) перед их передачей в модули ансамбля.',
    aqm_ensemble: 'Модули Ансамбля',
    aqm_ensemble_desc: 'Двойные модули XGBoost + CatBoost для регрессии (C6H6, CO) и классификации (AQI). Прогнозы усредняются для стабильности.',
    aqm_targets: 'Цели прогнозирования',
    aqm_regression: 'Регрессия',
    aqm_multiclass: 'Мульти-класс',
    aqm_hyperparameters: 'Гиперпараметры',

    // Models - DataPreprocessing
    dp_title: 'Конвейер предобработки данных',
    dp_subtitle: 'Инженерия признаков для заторов трафика',
    dp_desc: 'Преобразует необработанные данные датчиков трафика и контекстные входы в готовые для модели признаки с помощью конвейеров sklearn.',
    dp_preview: 'Предварительный просмотр набора данных',
    dp_uploadDesc: 'Загрузите CSV с данными о трафике для предварительного просмотра. Предобработка выполняется на стороне сервера во время вывода модели трафика.',
    dp_previewRows: 'Просмотр первых 20 строк',
    dp_rawPreview: 'Предварительный просмотр исходных данных',
    dp_pipelineArch: 'Архитектура конвейера',
    dp_step1: 'Необработанные данные',
    dp_step2: 'Временное извлечение',
    dp_step3: 'Импутация',
    dp_step4: 'Масштаб. / Кодирование',
    dp_step5: 'Готовая матрица',
    dp_temporalFeat: 'Временные признаки',
    dp_temp1: 'Циклическое кодиров. 24ч',
    dp_temp2: 'Циклическое кодиров. 7д',
    dp_temp3: 'Бинарный флаг выходных',
    dp_temp4: 'Флаг федеральных праздников США',
    dp_numeric: 'Числовые признаки',
    dp_numDesc: 'Медианная импутация → нормализация StandardScaler',
    dp_categorical: 'Категориальные признаки',
    dp_catDesc: 'Импутация по частоте → OneHotEncoder',

    // Models - GeoAIAccessibility
    geoai_title: 'Маршрутизатор доступности GeoAI',
    geoai_subtitle: 'Навигация в стиле GNN с приоритетом для колясок',
    geoai_desc: 'Механизм маршрутизации на основе графов, который строит граф с учетом доступности на основе данных узлов (тактильная плитка, доступность для колясок, профили бордюров/пандусов), применяет передачу сообщений в стиле GNN для сглаживания оценок, а затем запускает алгоритм Дейкстры со штрафами за доступность.',
    geoai_planRoute: 'Планировать маршрут',
    geoai_start: 'Начало (geoid или адрес)',
    geoai_dest: 'Назначение (geoid или адрес)',
    geoai_computing: 'Вычисление...',
    geoai_findRoute: 'Найти маршрут',
    geoai_routeResult: 'Результат маршрута',
    geoai_distance: 'Дистанция',
    geoai_time: 'Время',
    geoai_accessibility: 'Доступность',
    geoai_confidence: 'Уверенность',
    geoai_warnings: 'Предупреждения',
    geoai_routeSteps: 'Шаги маршрута',
    geoai_howItWorks: 'Как это работает',
    geoai_step1: '1. Оценка узлов',
    geoai_step1Desc: 'Каждый узел получает взвешенную оценку доступности на основе характеристик тактильности, доступности для колясок, бордюров и сигналов.',
    geoai_step2: '2. Передача сообщений',
    geoai_step2Desc: 'Оценки сглаживаются по топологии графа за счет итеративного смешивания соседних значений (3 раунда, 35% смешивание).',
    geoai_step3: '3. Маршрутизация Дейкстры',
    geoai_step3Desc: 'Кратчайший путь использует стоимость ребра = расстояние × штраф за доступность × штраф за уклон для оптимальных маршрутов для колясок.',
    geoai_featureWeights: 'Веса признаков доступности',
    geoai_feat1: 'Доступн. для колясок',
    geoai_feat2: 'Тактильная плитка',
    geoai_feat3: 'Бордюр / Пандус',
    geoai_feat4: 'Аудио сигналы',
    geoai_params: 'Параметры модели',
    geoai_param1: 'Шаги передачи сообщений',
    geoai_param2: 'Смешивание соседей',
    geoai_param3: 'Базовая скорость обхода',
    geoai_param4: 'Порог штрафа за уклон',

    // Models - IntegrationService
    int_title: 'Служба интеграции',
    int_subtitle: 'Оболочка вывода качества воздуха в реальном времени',
    int_desc: 'Готовая к производству служебная оболочка гибридной модели качества воздуха. Поддерживает скользящий буфер истории, автоматически дополняет короткие последовательности для вывода одиночных событий и возвращает результаты прогнозирования, сериализуемые в JSON.',
    int_simulate: 'Симулировать событие датчика',
    int_predResult: 'Результат прогноза',
    int_reqFlow: 'Поток запросов',
    int_step1: 'Событие датчика',
    int_step2: 'Буфер истории',
    int_step3: 'Заполнение посл.',
    int_step4: 'Вывод модели',
    int_step5: 'Ответ JSON',
    int_rollingBuffer: 'Скользящий буфер истории',
    int_bufferStrat: 'Стратегия буфера',
    int_bufferStratDesc: 'Дек фиксированного размера. Новые события добавляются, самые старые удаляются при заполнении.',
    int_autoPad: 'Автозаполнение',
    int_autoPadDesc: 'Короткие буферы заполняются дублированием самой ранней строки для достижения минимальной длины последовательности.',
    int_resSchema: 'Схема ответа',
    int_field: 'Поле',
    int_type: 'Тип',
    int_descTable: 'Описание',
    int_descCO: 'Уровень CO',
    int_descC6H6: 'Уровень C6H6',
    int_descAQI: 'Индекс качества воздуха',
    int_descCat: 'Категория AQI',

    // Models - TrafficModel
    traf_title: 'Модель заторов трафика',
    traf_subtitle: 'Классификатор RandomForest с подключаемым бэкендом',
    traf_desc: 'Мультиклассовый классификатор заторов, использующий ансамбль RandomForest. Принимает данные в реальном времени, включая количество автомобилей, скорости, занятость дорог, погоду, звуковой стресс (гудки) и уровень CO2, для предсказания Низких / Средних / Высоких заторов.',
    traf_predCongestion: 'Прогнозируемый затор',
    traf_congLevels: 'Уровни заторов',
    traf_descFree: 'Свободно движущийся трафик',
    traf_descMod: 'Умеренная загруженность',
    traf_descSev: 'Сильная пробка',
    traf_inputFeat: 'Группы входных признаков',
    traf_grp1: 'Состояние трафика',
    traf_grp2: 'Смесь ТС',
    traf_grp3: 'Контроль и контекст',
    traf_grp4: 'Стрессовые сигналы',
    traf_rfBackend: 'Бэкенд RandomForest',
    traf_p1: 'Оценщики',
    traf_p2: 'Макс. глубина',
    traf_p3: 'Мин. выборок лист',
    traf_p4: 'Вес класса',
    traf_plugDesign: 'Подключаемый дизайн',
    traf_plugDesc: 'Бэкенд модели следует простому протоколу ModelBackend (fit/predict). RandomForest можно заменить на BiLSTM или любую последовательную модель без изменения конвейера предварительной обработки или уровня API.',
  },
  kk: {
    // Existing
    settings: 'Баптаулар',
    profile: 'Профиль',
    appearance: 'Сыртқы түрі',
    language: 'Тіл',
    theme: 'Тақырып',
    light: 'Жарық',
    dark: 'Қараңғы',
    system: 'Жүйелік',
    save: 'Сақтау',
    saved: 'Сақталды!',
    email: 'Эл. пошта',
    role: 'Рөл',
    signOut: 'Шығу',
    settingsDesc: 'Аккаунт баптауларын басқарыңыз және тәжірибеңізді теңшеңіз.',
    profileDesc: 'Аутентификация жүйесінен алынған аккаунт ақпараты.',
    appearanceDesc: 'Платформаның сыртқы түрін реттеңіз.',
    languageDesc: 'Қалаған интерфейс тілін таңдаңыз.',
    themeDesc: 'Интерфейс үшін түс схемасын таңдаңыз.',
    citizen: 'Азамат',
    government: 'Мемлекеттік орган',
    emergency: 'Құтқару қызметі',
    volunteer: 'Волонтёр',
    admin: 'Әкімші',
    dashboard: 'Басқару тақтасы',
    welcomeBack: 'Қош келдіңіз',

    // Navbar & Sidebar
    nav_airQuality: 'Ауа сапасы моделі',
    nav_dataPrep: 'Деректерді өңдеу',
    nav_geoAI: 'GeoAI Қолжетімділігі',
    nav_integration: 'Интеграция қызметі',
    nav_traffic: 'Көлік қозғалысы моделі',
    nav_myHub: 'Менің хабым',
    nav_routingMap: 'Маршрут және карта',
    nav_eventsMap: 'Оқиғалар картасы',
    nav_volunteerBoard: 'Волонтёрлер тақтасы',
    nav_emergencies: 'ТЖ',
    nav_aiModels: 'ЖИ Модельдері',
    nav_about: 'Біз туралы',
    nav_pendingRole: 'Рөлді күту',
    nav_pending: 'Күтілуде',
    nav_lightMode: 'Жарық тақырып',
    nav_darkMode: 'Қараңғы тақырып',
    nav_signOut: 'Шығу',
    nav_signIn: 'Кіру',
    sidebar_navigation: 'Навигация',
    sidebar_activeRole: 'Белсенді рөл',

    // Footer
    footer_desc: "Қалаңыздың қолжетімділігін арттырыңыз. Қолайлы маршрут құрыңыз және жақын маңдағы еріктілермен лезде байланысыңыз.",
    footer_platform: 'Платформа',
    footer_signInReg: 'Кіру / Тіркелу',
    footer_interactiveMap: 'Интерактивті карта',
    footer_legal: 'Құқықтық ақпарат',
    footer_privacyPolicy: 'Құпиялылық саясаты',
    footer_termsService: 'Қолдану шарттары',

    // Landing Page
    landing_hero1: 'Қалаңыздың қолжетімділігін',
    landing_hero2: 'арттырыңыз.',
    landing_desc: 'Ең жақсы навигация құралы. Қолжетімді маршрут құрыңыз және қосымша көмек қажет болғанда еріктілермен лезде байланысыңыз.',
    landing_getStarted: 'Бастау',
    landing_planRouteText: 'Маршрутты жоспарлау',
    landing_startPoint: 'Бастапқы нүкте',
    landing_whereTo: 'Қайда бара жатырсыз?',
    landing_routeBtn: 'Маршрут',
    landing_planRouteBtn: 'Маршрут жоспары',
    landing_useCurrentLoc: 'Ағымдағы орынды пайдалану',
    landing_moveCurrentLoc: 'Ағымдағы орынға өту',

    // Auth
    auth_welcomeBack: 'Қайта оралуыңызбен',
    auth_join: 'sonar-ға қосылыңыз',
    auth_noAccount: "Аккаунтыңыз жоқ па? ",
    auth_hasAccount: "Аккаунтыңыз бар ма? ",
    auth_signUp: 'Тіркелу',
    auth_signIn: 'Кіру',
    auth_regSuccess: 'Тіркелу сәтті аяқталды! Өтінеміз, жүйеге кіріңіз.',
    auth_accountType: 'Аккаунт түрі',
    auth_govAuth: 'Мемлекеттік орган / Басқарма',
    auth_volunteerResp: 'Ерікті-құтқарушы',
    auth_emailAddr: 'Эл. пошта',
    auth_password: 'Құпия сөз',
    auth_processing: 'Өңделуде...',
    auth_createAccount: 'Аккаунт құру',

    // Profile Details
    profile_anonymous: 'Анонимді пайдаланушы',
    profile_edit: 'Профильді өңдеу',
    profile_cancel: 'Болдырмау',
    profile_saving: 'Сақталуда...',
    profile_personalInfo: 'Жеке ақпарат',
    profile_firstName: 'Аты',
    profile_egJohn: 'мыс. Азамат',
    profile_notSpecified: 'Көрсетілмеген',
    profile_lastName: 'Тегі (міндетті емес)',
    profile_egDoe: 'мыс. Азаматов',
    profile_demographics: 'Демография',
    profile_city: 'Қала (Орналасқан жері бойынша)',
    profile_egAlmaty: 'мыс. Алматы',
    profile_age: 'Жасы (Міндетті емес)',
    profile_egAge: 'мыс. 25',
    profile_yearsOld: 'жас',

    // Events & Map
    cat_infrastructure: 'Инфраструктура',
    cat_emergency: 'ТЖ',
    cat_urban: 'Қалалық орта',
    cat_events: 'Оқиғалар',
    catDesc_infrastructure: 'Құрылыс, құбырлар, жолдар',
    catDesc_emergency: 'Апаттар, өрт, құлаған ағаш',
    catDesc_urban: 'Қоқыс, жанбайтын шамдар',
    catDesc_events: 'Жәрмеңке, концерт, жол жабылуы',
    status_all: 'Барлық статустар',
    status_planned: 'Жоспарланған',
    status_active: 'Белсенді',
    status_resolving: 'Шешілуде',
    impact_low: 'Төмен',
    impact_medium: 'Орташа',
    impact_high: 'Жоғары',
    impactBadge_low: 'Төмен әсер',
    impactBadge_medium: 'Орташа әсер',
    impactBadge_high: 'Жоғары әсер',

    map_filters: 'Сүзгілер',
    map_all: 'Барлығы',
    map_eventsCount: 'оқиға',
    map_tapPin: '📍 Оқиға орнын белгілеу үшін картаны түртіңіз',
    map_goToLocation: 'Менің орналасқан жерім',
    map_reportEvent: 'Оқиға туралы хабарлау',

    modal_reportEvent: 'Оқиға туралы хабарлау',
    modal_aiRefine: 'ЖИ Жақсарту',
    modal_eventName: 'Оқиға атауы *',
    modal_egRoad: 'мыс. Абай көшесіндегі жол жөндеу',
    modal_desc: 'Сипаттама',
    modal_briefDesc: 'Не болып жатқанын қысқаша сипаттаңыз...',
    modal_refiningAI: 'ЖИ өңдеуде...',
    modal_refinedAI: '✓ Жақсартылды — ЖИ қайта іске қосу',
    modal_autoFillAI: 'Автотолтыру (ЖИ)',
    modal_aiAppliedMsg: 'ЖИ төмендегі өрістерді автоматты түрде толтырды. Тексеріп, қажет болса өзгертіңіз.',
    modal_category: 'Категория *',
    modal_photoVideo: 'Фото / Видео',
    modal_tapAddPhoto: 'Фото қосу үшін түртіңіз',
    modal_photoCredibility: 'Фотосурет сіздің есебіңізге сенімділікті арттырады',
    modal_timestamp: 'Құрылған уақыты: ',
    modal_addDetails: '🎯 Детальдар қосу (міндетті емес)',
    modal_impactLevel: 'Әсер ету деңгейі',
    modal_status: 'Статус',
    modal_quickTags: 'Жылдам тегтер',
    modal_submitting: 'Жіберілуде...',
    modal_submitReport: 'Есепті жіберу',

    panel_radius: ' радиус',
    panel_tags: 'Тегтер',
    panel_desc: 'Сипаттама',
    panel_trustScore: 'Сенім индексі',
    panel_confirm: 'Растаймын',
    panel_notHere: 'Бұл жерде жоқ',
    panel_reported: 'Хабарланды ',
    panel_timeUnknown: 'Белгісіз',
    panel_timeJustNow: 'Жаңа ғана',
    panel_timeMinsAgo: 'м бұрын',
    panel_timeHrsAgo: 'с бұрын',
    panel_timeDaysAgo: 'к бұрын',

    // Widgets (Chat, Gamification, MapRouting, Alerts)
    chat_serviceNotConnected: 'ЖИ қызметі әлі қосылмаған. Кейінірек қайта тексеріңіз.',
    chat_assistant: 'ЖИ көмекшісі',
    chat_poweredBy: 'OpenAI негізінде',
    chat_typeRequest: 'Сұрауыңызды енгізіңіз...',

    gamification_levelX: '{level} деңгейдегі ерікті',
    gamification_pts: 'Ұпай',
    gamification_helps: 'Көмек',
    gamification_lv: 'Деңг. ',
    gamification_rank: 'Дәреже',

    routing_title: 'Қолжетімді маршрут',
    routing_placeholder: 'Қайда барғыңыз келеді?',
    routing_routing: 'Маршрутты құру...',
    routing_routeBtn: 'Маршрут',
    routing_errorNoDest: 'Алдымен баратын жерді енгізіңіз.',
    routing_errorCalc: 'Қолжетімді маршрутты есептеу сәтсіз аяқталды.',
    routing_errorFetch: 'Маршрут нұсқауларын алу мүмкін болмады.',
    routing_geoAI: 'GeoAI Қолжетімділік анализі',
    routing_score: 'Баға: ',
    routing_next: 'Келесі: ',
    routing_moveToLoc: 'Ағымдағы орынға өту',

    alert_emergency: 'Төтенше жағдай туралы ескерту',

    // Dashboards - Admin
    admin_title: 'Әкімшілік басқару орталығы',
    admin_subtitle: 'Платформаға нақты уақыттағы шолу және оқиғаларды қадағалау.',
    admin_platformActive: 'Платформа белсенді',
    admin_totalUsers: 'Барлық тіркелген пайдаланушылар',
    admin_activeVolunteers: 'Белсенді еріктілер',
    admin_liveEvents: 'Тірі оқиғалар',
    admin_liveMap: 'Оқиғалар картасы',
    admin_tracking: 'Қадағалау',
    admin_active: 'белсенді',
    admin_recentFeed: 'Соңғы белсенділік тізбегі',
    admin_noRecentActivity: 'Жақында белсенділік жазылмаған.',
    admin_status: 'Мәртебесі: ',

    // Dashboards - Citizen
    citizen_title: 'Азаматтық қызметтер',
    citizen_welcomeText: 'Қош келдіңіз, {email}. Бүгін сіздің қозғалысыңызға қалай көмектесе аламыз?',
    citizen_reqAssistance: 'Физикалық көмек сұрау',
    citizen_reqAssistanceDesc: 'Егер сізге баспалдақпен көтерілу, көлікке отыру немесе қауіпті қиылыстан өту үшін шұғыл көмек қажет болса, жақын маңдағы тексерілген еріктілерге сұрау жіберіңіз.',
    citizen_broadcastReq: 'Көмек сұрауын тарату',
    citizen_connectingVol: 'Еріктілер желісіне қосылуда...',

    // Dashboards - Emergency
    emerg_title: 'Төтенше жағдайлар',
    emerg_activeAlerts: 'Белсенді сыни ескертулер',
    emerg_noActive: 'Белсенді төтенше жағдайлар бақыланбайды.',
    emerg_dispatch: 'Жіберу',
    emerg_dispatched: 'Жіберілді / Шешілуде',
    emerg_dispatchedAt: 'Жіберілген уақыты ',
    emerg_noDispatched: 'Жақында жіберілген бірліктер жоқ.',
    emerg_selfReportTitle: 'Апат туралы өзіндік есеп',
    emerg_eventCat: 'Оқиға санаты *',
    emerg_preciseLoc: 'Нақты орналасуы *',
    emerg_locPlaceholder: 'Мекенжай, қиылысу немесе GPS белгісі...',
    emerg_dateTime: 'Байқау күні мен уақыты *',
    emerg_severity: 'Ауырлық / Өзектілік деңгейі *',
    emerg_impact: 'Қоршаған ортаға әсері',
    emerg_detailedDesc: 'Егжей-тегжейлі сипаттама',
    emerg_descPlaceholder: 'Қосымша мәнмәтін (мысалы: сұйықтық ағуы, эвакуатор күту)...',
    emerg_visualEvid: 'Көзбен көретін дәлелдер',
    emerg_reporterInfo: 'Хабарлаушы туралы ақпарат',
    emerg_submitAnon: 'Жасырын жіберу',
    emerg_yourName: 'Өз атыңыз',
    emerg_contactOpt: 'Email немесе телефон (міндетті емес)',
    emerg_submitReport: 'Есепті жіберу',
    emerg_cat_traffic: 'Жол көлік оқиғасы',
    emerg_cat_road: 'Жол жөндеу',
    emerg_cat_poth: 'Шұңқыр',
    emerg_cat_tree: 'Құлаған ағаш',
    emerg_cat_flood: 'Су тасқыны',
    emerg_cat_event: 'Қоғамдық іс-шара',
    emerg_imp_lanes: 'Жолақтар жабылды',
    emerg_imp_side: 'Тротуар жабық',
    emerg_imp_power: 'Электр қуаты өшті',
    emerg_imp_traffic: 'Тығыз қозғалыс',
    emerg_imp_noise: 'Қатты шу',
    emerg_imp_hazard: 'Жаяу жүргіншілерге қауіп',
    emerg_sev_low: 'Төмен',
    emerg_sev_med: 'Орташа',
    emerg_sev_high: 'Жоғары',
    emerg_sev_crit: 'Сыни',

    // Dashboards - Government
    gov_title: 'Қалалық зияткерлік хаб',
    gov_subtitle: 'АИ-негізделген инфрақұрылым және мобилділік аналитикасы',
    gov_trafficAgent: 'Трафикті оңтайландыру агенті',
    gov_zonePlaceholder: 'Қала аумағын енгізіңіз...',
    gov_analyzing: 'Талдау жүргізілуде...',
    gov_runAnalysis: 'Талдауды іске қосу',
    gov_conf: 'Сенімділік: ',
    gov_aiRec: 'ЖИ Ұсынысы:',
    gov_liveMetrics: 'Тірі қала метрикалары',
    gov_routesReported: 'Хабарланған қолжетімді бағыттар',
    gov_volNetwork: 'Еріктілер желісінің көлемі',

    // Dashboards - Volunteer
    vol_title: 'Еріктілер хабы',
    vol_pointsLevel: '{points} Ұпай ({level} деңгей)',
    vol_activeSearching: 'Белсенді және іздеуде',
    vol_scanning: 'Сканерлеуде...',
    vol_activeReqs: 'Жақын маңдағы белсенді сұраулар',
    vol_noActiveReqs: 'Сіздің аймақта белсенді көмек сұраулары жоқ.',
    vol_assistanceAsap: 'Шұғыл көмек қажет.',
    vol_acceptMapRoute: 'Қабылдау және маршрут құру',

    // Models - AirQualityModel
    aqm_title: 'Ауа сапасының гибридті моделі',
    aqm_subtitle: 'LSTM + XGBoost + CatBoost ансамблі',
    aqm_desc: 'Қалалық ауа сапасын болжауға арналған гибридті тереңдетіп оқыту ансамблі. LSTM кодтаушысы ластаушы заттардың уақытша динамикасын түсіреді, содан кейін XGBoost және CatBoost модульдері соңғы регрессия мен жіктеуді орындайды — сенімді болжамдар үшін орташаланады.',
    aqm_runInference: 'Болжауды іске қосу',
    aqm_uploadCSV: 'Мына бағандары бар CSV жүктеп салыңыз: DATE_OCC, TIME_OCC, Lat, Lon, PT08.S1(CO), Temperature_C, RH% (or RH_%), Wind_Speed, C6H6(GT), AQI',
    aqm_clickToSelect: 'CSV таңдау үшін басыңыз',
    aqm_dragDrop: 'немесе осында сүйреңіз',
    aqm_processing: 'Өңделуде...',
    aqm_predict: 'Болжау',
    aqm_predictions: 'Болжамдар',
    aqm_row: 'Қатар',
    aqm_co: 'CO концентрациясы',
    aqm_c6h6: 'C6H6 концентрациясы',
    aqm_aqi: 'Ауа сапасының индексі (AQI)',
    aqm_category: 'Санат',
    aqm_architecture: 'Сәулет',
    aqm_lstm: 'LSTM кодтаушысы',
    aqm_lstm_desc: 'Көп қабатты LSTM сенсор көрсеткіштерінің жылжымалы терезелері арқылы уақытша тәуелділіктерді түсіріп, ықшам ендіруді шығарады.',
    aqm_fusion: 'Белгілерді біріктіру',
    aqm_fusion_desc: 'LSTM ендірмелері ансамбль басшыларына өтпес бұрын статикалық/лездік белгілермен (Ендік, Бойлық, Жел жылдамдығы) біріктіріледі.',
    aqm_ensemble: 'Ансамбль модульдері',
    aqm_ensemble_desc: 'Регрессия (C6H6, CO) және классификация (AQI) үшін қос XGBoost + CatBoost модульдері. Тұрақтылық үшін болжамдар орташаланады.',
    aqm_targets: 'Болжау мақсаттары',
    aqm_regression: 'Регрессия',
    aqm_multiclass: 'Мульти-класс',
    aqm_hyperparameters: 'Гиперпараметрлер',

    // Models - DataPreprocessing
    dp_title: 'Деректерді алдын ала өңдеу құбыры',
    dp_subtitle: 'Кептеліс үшін белгілер инженериясы',
    dp_desc: 'Шикі трафик сенсоры мен контекстік енгізулерді sklearn құбырлары арқылы модельге дайын белгілерге түрлендіреді.',
    dp_preview: 'Деректер жинағын алдын ала қарау',
    dp_uploadDesc: 'Шикі деректерді алдын ала қарау үшін трафик CSV жүктеп салыңыз. Алдын ала өңдеу трафик моделін шығару кезінде сервер жағында орындалады.',
    dp_previewRows: 'Алғашқы 20 жолды қарау',
    dp_rawPreview: 'Шикі деректерді алдын ала қарау',
    dp_pipelineArch: 'Құбыр сәулеті',
    dp_step1: 'Шикі сенсор деректері',
    dp_step2: 'Уақытша шығару',
    dp_step3: 'Импутация',
    dp_step4: 'Масштабтау / Кодтау',
    dp_step5: 'Дайын матрица',
    dp_temporalFeat: 'Уақытша белгілер',
    dp_temp1: 'Циклдік 24 сағ кодтау',
    dp_temp2: 'Циклдік 7 күндік кодтау',
    dp_temp3: 'Екілік демалыс күні жалауы',
    dp_temp4: 'АҚШ фед. мереке жалауы',
    dp_numeric: 'Сандық белгілер',
    dp_numDesc: 'Медиандық импутация → StandardScaler қалыпқа келтіру',
    dp_categorical: 'Категориялық белгілер',
    dp_catDesc: 'Жиілік бойынша импутация → OneHotEncoder',

    // Models - GeoAIAccessibility
    geoai_title: 'GeoAI Қолжетімділік маршрутизаторы',
    geoai_subtitle: 'Мүгедектер арбасы үшін бірінші GNN стиліндегі навигация',
    geoai_desc: 'Түйін деректерінен (тактильді төсеу, арбаға қолжетімділік, жиек/пандус профильдері) қолжетімділікті ескеретін график құратын, ұпайларды тегістеу үшін GNN рухындағы хабарлама жіберуді қолданатын, содан кейін қолжетімділік айыппұлдары бар Дейкстра алгоритмін іске қосатын графикке негізделген маршрутизатор.',
    geoai_planRoute: 'Маршрутты жоспарлау',
    geoai_start: 'Бастау (geoid немесе мекенжай)',
    geoai_dest: 'Тағайындау (geoid немесе мекенжай)',
    geoai_computing: 'Есептелуде...',
    geoai_findRoute: 'Маршрутты табу',
    geoai_routeResult: 'Маршрут нәтижесі',
    geoai_distance: 'Қашықтық',
    geoai_time: 'Уақыт',
    geoai_accessibility: 'Қолжетімділік',
    geoai_confidence: 'Сенімділік',
    geoai_warnings: 'Ескертулер',
    geoai_routeSteps: 'Маршрут қадамдары',
    geoai_howItWorks: 'Бұл қалай жұмыс істейді',
    geoai_step1: '1. Түйіндерді бағалау',
    geoai_step1Desc: 'Әрбір түйін тактильділік, арбаға қолжетімділік, бордюр және сигнал сипаттамаларынан өлшенген қолжетімділік ұпайын алады.',
    geoai_step2: '2. Хабарлама жіберу',
    geoai_step2Desc: 'Ұпайлар көршілес мәндерді қайталанатын араластыру арқылы графиктің топологиясы бойынша тегістеледі (3 раунд, 35% араластыру).',
    geoai_step3: '3. Дейкстра бағыттауы',
    geoai_step3Desc: 'Ең қысқа жол мүгедектер арбасына оңтайлы маршруттар үшін: жиек құны = қашықтық × қолжетімділік айыппұлы × еңіс айыппұлы.',
    geoai_featureWeights: 'Қолжетімділік белгілерінің салмақтары',
    geoai_feat1: 'Арбаға қолжетімділік',
    geoai_feat2: 'Тактильді төсеу',
    geoai_feat3: 'Бордюр / Пандус',
    geoai_feat4: 'Аудио сигналдар',
    geoai_params: 'Модель параметрлері',
    geoai_param1: 'Хабар жеткізу қадамдары',
    geoai_param2: 'Көршілерді араластыру',
    geoai_param3: 'Негізгі өту жылдамдығы',
    geoai_param4: 'Еңіс айыппұлының шегі',

    // Models - IntegrationService
    int_title: 'Интеграция қызметі',
    int_subtitle: 'Нақты уақыттағы ауа сапасын шығару қабықшасы',
    int_desc: 'Өндіріске дайын ауа сапасының гибридті моделінің қызметтік қабықшасы. Сырғымалы тарих буферін сақтайды, бір оқиға шығару үшін қысқа тізбектерді автоматты түрде толтырады және JSON форматына түрленетін болжам нәтижелерін қайтарады.',
    int_simulate: 'Сенсор оқиғасын модельдеу',
    int_predResult: 'Болжам нәтижесі',
    int_reqFlow: 'Сұраныс ағыны',
    int_step1: 'Сенсор оқиғасы',
    int_step2: 'Тарих буфері',
    int_step3: 'Тізбекті толтыру',
    int_step4: 'Модель қорытындысы',
    int_step5: 'JSON жауабы',
    int_rollingBuffer: 'Сырғымалы тарих буфері',
    int_bufferStrat: 'Буфер стратегиясы',
    int_bufferStratDesc: 'Бекітілген өлшемді дек. Жаңа оқиғалар қосылады, толған кезде ең ескісі шығарылады.',
    int_autoPad: 'Авто-толтыру',
    int_autoPadDesc: 'Қысқа буферлер минималды тізбек ұзындығына жету үшін ең ерте қатарды қайталау арқылы толтырылады.',
    int_resSchema: 'Жауап схемасы',
    int_field: 'Өріс',
    int_type: 'Түр',
    int_descTable: 'Сипаттама',
    int_descCO: 'CO деңгейі',
    int_descC6H6: 'C6H6 деңгейі',
    int_descAQI: 'Ауа сапасының индексі',
    int_descCat: 'AQI санаты',

    // Models - TrafficModel
    traf_title: 'Жол кептелісі моделі',
    traf_subtitle: 'Қосылатын бэкенді бар RandomForest классификаторы',
    traf_desc: 'RandomForest ансамблін қолданатын көп класты кептеліс классификаторы. Төмен / Орташа / Жоғары кептелісті болжау үшін нақты уақыттағы трафик көрсеткіштерін, соның ішінде көлік санын, жылдамдықты, жолды толтыруды, ауа райын, акустикалық стрессті (дыбыс сигналдары) және CO2 деңгейлерін қабылдайды.',
    traf_predCongestion: 'Болжанған кептеліс',
    traf_congLevels: 'Кептеліс деңгейлері',
    traf_descFree: 'Еркін қозғалыстағы көлік',
    traf_descMod: 'Орташа кептеліс',
    traf_descSev: 'Қатты кептеліс',
    traf_inputFeat: 'Кіріс белгілер топтары',
    traf_grp1: 'Трафик күйі',
    traf_grp2: 'Көлік құрамы',
    traf_grp3: 'Бақылау және контекст',
    traf_grp4: 'Стресс сигналдары',
    traf_rfBackend: 'RandomForest Бэкенд',
    traf_p1: 'Бағалаушылар',
    traf_p2: 'Макс. тереңдік',
    traf_p3: 'Мин. жапырақ үлгілері',
    traf_p4: 'Сlass салмағы',
    traf_plugDesign: 'Қосылатын дизайн',
    traf_plugDesc: 'Модельдің бэкенді қарапайым ModelBackend протоколын ұстанады (fit/predict). RandomForest алдын ала өңдеу құбырын немесе API қабатын түртпестен BiLSTM немесе кез келген тізбек моделімен ауыстырылуы мүмкін.',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('app-language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
